require:
  - rubocop-performance

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop/rspec.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: disable
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/HashAlignment:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false
